### ISSUE TITLE
Disable profile areas

### ISSUE THREAD

**Issue by mariannemyers** [mariannemyers/slush-marklogic-dotnet#12]
Since we do not have the concept of a user logged in for 0.1, disable the profile widgets on each of the templates.  We will be using these in the future, so for now comment out that code in the Angular template.

**Comment by mfgumban** [comment]
Sections that were commented out can be identified by searching the text "START_DISABLED_PROFILE".  For sections that contained HTML comments, their tags were replaced with "<!== ... ==>" to compensate.  When reverting back this change, replace "==" with "--".
