### ISSUE TITLE
.NET Core Version 1.1.0 no longer uses project.json

### ISSUE THREAD

**Issue by mfgumban** [mariannemyers/slush-marklogic-dotnet#26]
.NET Core Version 1.1.0 no longer recognizes project.json; instead it requires a .csproj or solution file, just like VS before.  The current workaround is to run `dotnet migrate` before `dotnet run` to create a .csproj.

Possibly generate the .csproj from slush to remove the need to migrate.

**Comment by mariannemyers** [comment]
Migrated an existing project to capture a valid .csproj and added this to the project.  The file is renamed to match the name of the app chosen by the user.  Removed project.json.
